import { ISeedWidget } from './widget-seed.interface';

export const DEFAULT_WIDGET_LAYOUT = 'defaultWidgetLayout';

export const WidgetTypes: ISeedWidget[] = [
  {
    code: 1,
    title: 'Check in work from home',
    description: 'Check in work from home',
    defaultHeight: 2,
    defaultWidth: 2,
  },
  {
    code: 2,
    title: 'Tin tức mới nhất',
    description: 'Tin tức mới nhất',
    defaultHeight: 3,
    defaultWidth: 3,
  },
  {
    code: 3,
    title: 'Tin nhanh',
    description: 'Tin nhanh',
    defaultHeight: 4,
    defaultWidth: 3,
  },
  {
    code: 4,
    title: 'Thông tin cá nhân',
    description: 'Thông tin cá nhân',
    defaultHeight: 3,
    defaultWidth: 3,
  },
  {
    code: 5,
    title: 'Faces',
    description: 'Faces',
    defaultHeight: 2,
    defaultWidth: 2,
  },
  {
    code: 6,
    title: 'Tổng quỹ phạt',
    description: 'Tổng quỹ phạt',
    defaultHeight: 1,
    defaultWidth: 2,
  },
  {
    code: 7,
    title: 'Unlock Timesheet',
    description: 'Unlock Timesheet',
    defaultHeight: 2,
    defaultWidth: 2,
  },
  {
    code: 8,
    title: 'Danh sách vi phạm',
    description: 'Danh sách vi phạm',
    defaultHeight: 2,
    defaultWidth: 2,
  },
  {
    code: 9,
    title: 'Danh sách task cần hoàn thành trong ngày',
    description: 'Danh sách task cần hoàn thành trong ngày',
    defaultHeight: 4,
    defaultWidth: 2,
  },
  {
    code: 10,
    title: 'Danh sách request cần approve',
    description: 'Danh sách request cần approve',
    defaultHeight: 4,
    defaultWidth: 3,
  },
  {
    code: 11,
    title: 'Top quỹ phạt',
    description: 'Top quỹ phạt',
    defaultHeight: 2,
    defaultWidth: 2,
  },
  {
    code: 12,
    title: 'Total Unlock Timesheet',
    description: 'Total Unlock Timesheet',
    defaultHeight: 1,
    defaultWidth: 2,
  },
  {
    code: 13,
    title: 'Traditional Albums',
    description: 'Traditional Albums',
    defaultHeight: 2,
    defaultWidth: 3,
  },
  {
    code: 14,
    title: 'Log Timesheet Today',
    description: 'Log Timesheet Today',
    defaultHeight: 2,
    defaultWidth: 2,
  },
  {
    code: 15,
    title: 'Xin đi muộn/nghỉ phép',
    description: 'Xin đi muộn/nghỉ phép',
    defaultHeight: 4,
    defaultWidth: 4,
  },
  {
    code: 16,
    title: 'Widget link sang các tool khác',
    description: 'Widget link sang các tool khác',
    defaultHeight: 1,
    defaultWidth: 2,
  },
  {
    code: 17,
    title: 'Tin tức',
    description: 'Tin tức',
    defaultHeight: 3,
    defaultWidth: 3,
  },
  {
    code: 18,
    title: 'Sự kiện',
    description: 'Sự kiện',
    defaultHeight: 3,
    defaultWidth: 3,
  },
  {
    code: 19,
    title: 'Hướng dẫn',
    description: 'Hướng dẫn',
    defaultHeight: 3,
    defaultWidth: 3,
  },
  {
    code: 20,
    title: 'Quy định',
    description: 'Quy định',
    defaultHeight: 3,
    defaultWidth: 3,
  },
];
